name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Get changed Python files
      id: changes
      run: |
        git fetch origin main
        CHANGED=$(git diff --name-only origin/main...HEAD | grep '\.py$' || true)
        echo "changed_files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run pylint
      if: steps.changes.outputs.changed_files != ''
      timeout-minutes: 10
      run: |
        echo "${{ steps.changes.outputs.changed_files }}" | xargs pylint

    - name: No Python files changed
      if: steps.changes.outputs.changed_files == ''
      run: echo "No Python files changed — skipping pylint."
